global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'zai-inventory-api'
    static_configs:
      - targets: ['inventory-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
