database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "inventory"

api:
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  enable_cors: true
  enable_auth: false

inventory:
  allow_negative_stock: false
  default_location: "DEFAULT"
  audit_enabled: true
  low_stock_threshold: 10
  alert_timeout_hours: 24

log:
  level: "info"
  format: "json"
  output_path: "stdout"
